Removes releases < v0.20
pomerium/documentation pull request #1416
Opened 2024-05-20 23:17 UTC by ZPain8464

This PR removes Core and Enterprise changelogs and upgrade guides up to v0.20. 

Related to https://github.com/pomerium/internal/issues/1798.

2024-05-21 00:04 UTC, kenjenkins commented
It sounds like https://github.com/pomerium/internal/issues/1798 is describing the links shown at [/docs/versions](https://deploy-preview-1416--pomerium-docs.netlify.app/docs/versions). I still see links going back as far as v0.10 there.

2024-06-04 16:05 UTC, desimone commented
Yeah, I don't think we need to _scrub_ the changelog here but rather the versions link list.

2024-06-04 16:05 UTC, desimone requested changes
Yeah, I don't think we need to scrub the changelog here but rather the versions link list.

2024-06-04 16:11 UTC, ZPain8464 commented
Ah I see, I'll update this PR to remove the archived versions links up to v0.20, and restore the changelogs and upgrade guides.

2024-06-07 17:51 UTC, kenjenkins approved these changes

2024-06-07 18:12 UTC, ZPain8464 commented
@desimone looks like you need to approve the changes to merge.

2024-06-12 15:19 UTC, desimone approved these changes

2024-06-12 15:41 UTC, merged