Zpain8464 poc update
pomerium/documentation pull request #161
Opened 2022-11-14 23:35 UTC by ZPain8464

Updated the PoC guide based on the changes discussed in ZenHub.

2022-11-15 01:47 UTC, desimone requested changes

2022-11-15 15:36 UTC, ZPain8464 commented on content/docs/install/quickstart.mdx
> +![user details page](./img/user-details-page.png)
I installed Shottr, WAY cleaner. I'm updating the image.

2022-11-15 21:42 UTC, ZPain8464 commented
@desimone and @calebdoxsey apologies on the confusion with the HedgeDoc guide and the PoC/Quickstart update – I'll create feature branches for updates going forward. 

I've added cleaner images to both docs and created a HedgeDoc subdir for images. Please let me know if anything else needs updating and I'll be happy to jump on it!

2022-11-16 16:16 UTC, calebdoxsey commented
Quickstart LGTM

2022-11-16 17:22 UTC, desimone approved these changes

2022-11-16 17:53 UTC, desimone requested changes

2022-11-16 17:53 UTC, desimone commented on content/docs/install/quickstart.mdx
> +![hsts error](./img/hsts-error.png)
```suggestion
![self-signed warning](./img/hsts-error.png)
```

2022-11-16 17:53 UTC, desimone commented on content/docs/install/quickstart.mdx
> +When navigating to the `https://verify.localhost.pomerium.io` route defined in your policy, you may encouter the following HSTS error:
```suggestion
When navigating to the `https://verify.localhost.pomerium.io` route defined in your policy, you may encounter the following self-signed certificate warning:
```

2022-11-16 17:53 UTC, desimone commented on content/docs/install/quickstart.mdx
> +### Handle HSTS Errors
```suggestion
### Handle Self-Signed Certificate Warning
```

2022-11-21 21:21 UTC, desimone requested changes
Lots of unrelated changes. Looks like you branched off an old main, then did a soft reset?

2022-11-22 18:32 UTC, ZPain8464 commented
@desimone hopefully this is the final push needed to get this up to date. Requesting review.

2022-11-22 18:35 UTC, desimone approved these changes
🥳

2022-11-22 19:54 UTC, merged