Docs: updates component level docs
pomerium/documentation pull request #367
Opened 2023-02-01 23:02 UTC by ZPain8464

Updates component level docs. I'd like to get @calebdoxsey and @wasaga to take a look and offer any suggestions or corrections as they see fit. Databroker, for instance, could be fleshed out more. 

The diagram I'm working on will incorporate some of these steps as well.

2023-02-02 15:43 UTC, calebdoxsey requested changes

2023-02-02 15:43 UTC, calebdoxsey commented on content/docs/internals/architecture.md
> +1. The Proxy service receives the request and redirects it to the Authorization service before proxying it
it does not redirect it to the Authorization service. It makes a gRPC call to the Authorization service which evaluates policy.

2023-02-02 15:43 UTC, calebdoxsey commented on content/docs/internals/architecture.md
> +1. After the Authentication service verifies the client’s identity and saves a local session cookie, the Proxy service redirects the session data to the Databroker service
it does not redirect the session data to the Databroker service. It makes a gRPC call to the Databroker service to save the session.

2023-02-02 15:43 UTC, calebdoxsey commented on content/docs/internals/architecture.md
> +1. Sends an HTTP request on behalf of the client to the IdP
It redirects the user to the identity provider.

2023-02-02 15:43 UTC, calebdoxsey commented on content/docs/internals/architecture.md
> +1. Verifies user identity after the session expires
After a session expires its as if the user is no longer logged in. Authenticate merely runs the login process again. It doesn't verify the user identity.

2023-02-02 15:43 UTC, calebdoxsey commented on content/docs/internals/architecture.md
> +1. The Authorization service first looks for a session cookie, which contains the client’s JWT. If no session cookie is present, the Authorization service sends a request to the Authentication servic
The Authorization service returns a Redirect response. The browser makes the request to the Authenticate service.

2023-02-02 15:43 UTC, calebdoxsey commented on content/docs/internals/architecture.md
> +1. Once a session cookie is in place, the Proxy service redirects the request to the Authorization service so it can determine permissions based on JWT claims and policy.
The Proxy service does not redirect the request to the Authorization service. It makes a gRPC call.

2023-02-02 15:43 UTC, calebdoxsey commented on content/docs/internals/architecture.md
> +1. With each subsequent request, the Authorization service checks the session expiration time and communicates session changes to the Databroker.
The Authorization service does not communicate session changes to the Databroker.

2023-02-02 15:43 UTC, calebdoxsey commented on content/docs/internals/architecture.md
> +- Once a client is authenticated, the Proxy server redirects the session data and identity information to the Databroker. The Databroker persists the data.
The Proxy service does not redirect the session data and identity information. It makes a gRPC call to the Databroker to save session data.

2023-02-02 15:43 UTC, calebdoxsey commented on content/docs/internals/architecture.md
> +- The Databroker streams authoritative session and identity data to the Authorization service, keeping the two services in sync.
The Databroker no longer streams authoritative session and identity data to the Authorization service. That data is queried on-demand by the Authorization service.

2023-02-02 20:55 UTC, calebdoxsey approved these changes

2023-02-06 17:46 UTC, merged

2023-02-06 20:10 UTC, cmo-pomerium reviewed
LGTM