Docs: updates request flow diagram
pomerium/documentation pull request #368
Opened 2023-02-02 20:48 UTC by ZPain8464

I honestly think the sequence diagram is the best approach to explain interactions between components. I revamped the current one so it's easier to read (I added color-coded services and more context). I also include 3 steps in the diagram that are explained beneath it, but they are somewhat repetitive if you read the Components section as well. 

Another thing worth noting is the "miro" watermark in the bottom-right corner. I can update to a free trial to see if I can save the image in higher resolution without the watermark for the time being. If everyone is OK with this new diagram, I'll upgrade and replace the current image. 

Tagging @desimone, @calebdoxsey, and @wasaga for visibility.

2023-02-07 16:42 UTC, calebdoxsey approved these changes
LGTM

2023-02-07 19:29 UTC, wasaga approved these changes

2023-02-10 19:36 UTC, desimone commented on content/docs/internals/architecture.md
> +# cspell:ignore Authorization
```suggestion
# cspell:ignore Authorization
```

Probably should just add tthis to `cspell.json` instead?

2023-02-10 19:39 UTC, desimone requested changes
There are two flow diagrams but only one is used. Also, SVG or a high quality png would be better than jpeg i think.

2023-02-10 19:39 UTC, desimone commented on content/docs/internals/architecture.md
> +![pomerium architecture diagram](./img/architecture/pomerium-request-flow-2.jpg)
```suggestion
![pomerium architecture diagram](./img/architecture/pomerium-request-flow-2.jpg)
```

SVG would probably be better if you can export it.

2023-02-10 19:39 UTC, desimone commented on content/docs/internals/architecture.md
> +After the client signs in, the IdP exchanges an authorization code with the Authentication service. The Authentication service uses the code to get OAuth tokens and OIDC claims from the IdP.
```suggestion
After the client signs in, the IdP exchanges an authorization code with the Authentication service. The Authentication service uses the code to get OAuth tokens and OIDC claims from the IdP.
```

> authorization code
we should probably link to the oidc spec which describes code flow.

2023-02-10 23:28 UTC, desimone approved these changes

2023-02-14 13:39 UTC, merged