Docs: updates core docker quickstart signing key and verify screenshot
pomerium/documentation pull request #384
Opened 2023-02-08 21:53 UTC by ZPain8464

2023-02-08 22:08 UTC, desimone requested changes

2023-02-08 22:08 UTC, desimone commented on content/examples/config/config.docker.yaml.md
> +idp_provider_url: REPLACE_ME
I don't think we need this?

2023-02-08 22:08 UTC, desimone commented on content/examples/docker/basic.docker-compose.yml.md
> +    networks:
Maybe we should add a comment that this is only required when the `localhost.pomerium.io` domain is used?

2023-02-09 16:28 UTC, wasaga approved these changes

2023-02-09 17:40 UTC, ssveta7ak approved these changes

2023-02-09 18:11 UTC, desimone approved these changes

2023-02-09 20:40 UTC, merged