Docs: adds release notes for v21 console
pomerium/documentation pull request #389
Opened 2023-02-10 21:07 UTC by ZPain8464

This definitely needs a review, but from what I could see on the changelog there were only two major callouts and a ton of fixes.

2023-02-13 23:44 UTC, calebdoxsey approved these changes

2023-02-14 17:41 UTC, desimone requested changes

2023-02-14 17:41 UTC, desimone commented on content/docs/releases/enterprise/upgrading.mdx
> +### Breaking
Put breaking at the top. Match header (h4 vs h3)

2023-02-14 21:05 UTC, desimone approved these changes

2023-02-14 21:05 UTC, merged