Docs: adds wildcard from routes config reference
pomerium/documentation pull request #585
Opened 2023-04-26 19:48 UTC by ZPain8464

Adds a Wildcard From Routes reference page. However, if this is Enterprise only it may make more sense to put this in the GUI Configuration page until we migrate all Console references/Settings to the main Reference page.

2023-04-26 20:37 UTC, calebdoxsey requested changes

2023-04-26 20:37 UTC, calebdoxsey commented on content/docs/reference/routes/from.md
> +**Wildcard From Routes** supports the use of a wildcard asterisk (`*`) prefixed to the domain name portion of a `from` URL.
it can occur anywhere within the domain name portion. It doesn't have to be a prefix.

2023-04-27 15:26 UTC, calebdoxsey approved these changes

2023-04-27 16:47 UTC, desimone commented on content/docs/reference/routes/from.md
> +Wildcard From Routes (`*`) may take precedence over non-wildcard routes regardless of their ordering. (To be safe, specify the ordering by using Wildcard From Routes after non-wildcard routes.)
We should mention that precedence of routes of more specified routes supersedes that of less specific wildcard routes.

2023-04-27 16:47 UTC, desimone commented on content/docs/reference/routes/from.md
> +**Kubernetes:** Not supported <br/>
This is unofficially supported but the behavior of the two implementations are different. The behavior will be different than what is defined in the kubernetes docs. We should warn users that the behavior may be undefined. 

\cc @wasaga to describe distinction.

2023-05-01 17:05 UTC, desimone approved these changes

2023-05-01 17:29 UTC, merged