Docs: adds v22 Console changelog
pomerium/documentation pull request #595
Opened 2023-05-02 20:40 UTC by ZPain8464

2023-05-02 21:01 UTC, calebdoxsey approved these changes

2023-05-02 21:02 UTC, desimone requested changes

2023-05-02 21:02 UTC, desimone commented on content/docs/releases/enterprise/changelog.mdx
> +- Wildcard From Routes support allows you to define multiple near-identical external `from` routes that point to the same internal `to` route.
Add link to the new reference pages on wildcarding.

2023-05-02 21:02 UTC, desimone commented on content/docs/releases/enterprise/changelog.mdx
> +- More consistent and linear memory performance significantly reduces memory consumption, especially in environments with rapidly changing configurations.
Add link to the github PR for RDS changes

2023-05-03 02:25 UTC, desimone requested changes

2023-05-03 02:25 UTC, desimone commented on content/docs/releases/enterprise/changelog.mdx
> +- [Hosted Authenticate Service](/docs/capabilities/hosted-authenticate-service.md) runs by default. [Self-hosted authenticate service](/docs/capabilities/self-hosted-authenticate-service.md) is still
```suggestion
- [Hosted Authenticate Service](/docs/capabilities/hosted-authenticate-service.md) will now be used by default to handle single-sign-on. Pomerium hosts this service as a convenience to its users; not identity provider configuration or authenticate service url needs to be specified if the hosted authenticate service is used. [Self-hosted authenticate service](/docs/capabilities/self-hosted-authenticate-service.md) is still available for users who want to configure their own identity provider and authenticate service URL.
```

2023-05-03 16:56 UTC, desimone approved these changes

2023-05-03 17:16 UTC, merged