Docs: adds v22 upgrade guide
pomerium/documentation pull request #596
Opened 2023-05-02 21:05 UTC by ZPain8464

2023-05-02 21:10 UTC, desimone requested changes
Missing the new wildcard functionality and a callout that it is `beta` support

2023-05-02 21:10 UTC, desimone commented on content/docs/releases/upgrading.mdx
> +The [Hosted Authenticate Service](/docs/capabilities/hosted-authenticate-service.md) provides a hosted authenticate service URL and hosted identity provider. The [Self-Hosted Authenticate Service](/d
```suggestion
The [Hosted Authenticate Service](/docs/capabilities/hosted-authenticate-service.md) replaces the need for an explicitly authenticate service URL / hosted identity provider. Users can now get started without needing their own identity provider, or authenticate service. 

The [Self-Hosted Authenticate Service](/docs/capabilities/self-hosted-authenticate-service), which requires a self-hosted authenticate service URL and identity provider, is still supported for users that prefer to host these services themselves.
```

Clear-er-er?

2023-05-02 21:43 UTC, ZPain8464 commented
@desimone sorry for some reason I thought it wildcard support was only for Enterprise. I'll add.

2023-05-02 22:21 UTC, calebdoxsey approved these changes

2023-05-02 23:34 UTC, desimone commented on content/docs/releases/upgrading.mdx
> +The [Hosted Authenticate Service](/docs/capabilities/hosted-authenticate-service.md) replaces the need for an explicit authenticate service URL and hosted identity provider. Users can now get started
```suggestion
The [Hosted Authenticate Service](/docs/capabilities/hosted-authenticate-service.md) replaces the need for a self-hosted authenticate service and explicit third-party identity provider configuration. Users can now get started without including their own identity provider, or authenticate service.
```

2023-05-02 23:34 UTC, desimone commented on content/docs/releases/upgrading.mdx
> +The [Self-Hosted Authenticate Service](/docs/capabilities/self-hosted-authenticate-service), which requires a self-hosted authenticate service URL and identity provider, is still supported for users
The sentence is kinda awkward.

2023-05-02 23:34 UTC, desimone commented on content/docs/releases/upgrading.mdx
> +[Wildcard From Routes](/docs/reference/routes/from#wildcard-from-routes) support allows you to define multiple near-identical external `from` routes that point to the same internal `to` route. Wildca
> Wildcard From Routes

Is awkwardly written. The feature allows wildcard syntax (e.g. `*`) in the `From` route configuration option.

2023-05-03 16:56 UTC, desimone approved these changes

2023-05-03 17:16 UTC, merged