Docs: sidebar restructure
pomerium/documentation pull request #644
Opened 2023-05-26 15:41 UTC by ZPain8464

This PR replaces `/docs/releases` with `/docs/deploy`. The **Deploy** sidebar houses the following sections:
- Pomerium Core
- Kubernetes
- Enterprise

2023-05-26 16:41 UTC, ZPain8464 commented
The `redirects` file would need to updated as well. But I think it might be easier to merge this (if everyone is happy with it so far) and fix breaking links as they appear. (Similar to the last big re-org).

2023-05-30 03:27 UTC, desimone requested changes
Overall, I think this is a good change. 

- I think we should move “Clients” from under “Pomerium core” to being under “Deploy” at the bottom of the list. 
- Move “To production” from Enterprise to under Deploy and move it to the very bottom of the list. 


Otherwise, LGTM pending … yeah, that’s going to be a lot of redirects. :/

2023-05-30 15:52 UTC, desimone approved these changes

2023-05-30 15:52 UTC, desimone commented on static/_redirects
> +/docs/overview/upgrading /docs/deploy/core/upgrading
Should we set a catch all for `/deploying/*` and `/releases/*`?

2023-05-31 14:07 UTC, merged