Update identity verification page
pomerium/documentation pull request #658
Opened 2023-06-02 00:09 UTC by kenjenkins

Restructure the page to emphasize the SDK examples. Add an example of verification using the Go SDK. Replace the javascript example with the React example from the JS SDK page. (I had to rename the file to the .mdx extension in order to do this, but I've done the rename in a separate commit, so looking at the diff of just the second commit should give a better picture of the actual changes.)

Emphasize the recommended JWT verification steps (signature, timestamp, and audience/issuer).

Update the note about audience and issuer to mention the change in behavior with respect to the issuer claim (fixes #654). Move the bit about additional claims right after the table describing the default claims.

Remove the jwks.json example output that showed a different signing algorithm. Add a note that the jwks.json endpoint requires setting a signing key explicitly.

Add a cross-reference link to the 'JWT Claim Headers' option from the 'Pass Identity Headers' option.

2023-06-02 13:12 UTC, ZPain8464 requested changes

2023-06-02 13:13 UTC, ZPain8464 commented
@kenjenkins I left a few small suggestions, otherwise this looks great to me. Thanks for taking this on!

2023-06-02 17:21 UTC, desimone commented on content/docs/capabilities/getting-users-identity.mdx
> +When the [Pass Identity Headers] route option is enabled, the user's associated identity information will be included in a signed attestation JWT. This JWT is added to each upstream request in the he
`/.pomerium` is correct.

2023-06-02 17:21 UTC, desimone commented on content/docs/capabilities/getting-users-identity.mdx
> +```
Alternatively, we could put the actual go code into a go-sdk guide which maybe would be more appropriate for this code block and instead link? I'll leave to you.

2023-06-02 17:41 UTC, ZPain8464 commented on content/docs/capabilities/getting-users-identity.mdx
> +```
I think for now we can just leave the code block in the guide, and I'll add a follow-up issue to create a Go SDK guide. Once it's done, we can update this page to link to the guide.

2023-06-02 18:20 UTC, kenjenkins commented on content/docs/capabilities/getting-users-identity.mdx
> +```
Moved to a new file examples/go-sdk/go-app.md.

2023-06-02 18:35 UTC, kenjenkins commented
Oh hang on, does the file extension actually matter? I thought I needed it to be .mdx in order to do the `import` stuff, but it seems to be working either way (at least when I run it locally).

2023-06-02 19:58 UTC, desimone commented
I believe `mdx` is only required if you are importing files. I don't think it's required, and yea -- would be ideal to preserve diff here to review more easily what was changed.

2023-06-05 12:53 UTC, ZPain8464 approved these changes

2023-06-05 15:41 UTC, desimone approved these changes

2023-06-05 15:56 UTC, merged